workflows:
  ios-app-store:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nuclearmotd.app
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_APPLE_ID: "6759457546"

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS release
        script: |
          flutter build ios --release \
            --dart-define=ENVIRONMENT=production \
            --no-codesign

      - name: Create Xcode archive
        script: |
          xcode-project use-profiles
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=8DGSM5PS96

      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --archive-path build/Runner.xcarchive

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
